version: "3.9"
services:
  web:
    build: ./WebApi
    ports:
      - 5000:80
    links:
      - db

  db:
    image: "postgres"
    environment: 
        POSTGRES_DB: "WeatherApp"
        POSTGRES_PASSWORD: "password"
    ports:
        - 5432:5432
    volumes:
        - db-data:/var/lib/postgresql/data
volumes:
  db-data: